services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: vpic
      POSTGRES_PASSWORD: vpic_password
      POSTGRES_DB: vpic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  db-init:
    build: .
    restart: "no"
    depends_on:
      db:
        condition: service_started
    command: ["python", "-m", "vin_api.scraper.db_updater"]
    environment:
      - DATABASE_URL=postgresql+psycopg://vpic:vpic_password@db:5432/vpic_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vpic
      - POSTGRES_PASSWORD=vpic_password
      - POSTGRES_DB=vpic_db

  api:
    build: .
    restart: always
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://vpic:vpic_password@db:5432/vpic_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=vpic
      - POSTGRES_PASSWORD=vpic_password
      - POSTGRES_DB=vpic_db

volumes:
  postgres_data:
